name: trainerpro
description: Aplicaci칩n de entrenamiento personal
publish_to: 'none' # No publicar en pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI y dise침o
  cupertino_icons: ^1.0.6
  lucide_icons: 0.257.0
  google_fonts: ^6.1.0
  
  # Estado y persistencia
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Navegaci칩n
  go_router: ^13.0.1
  
  # Utilidades
  intl: ^0.19.0
  uuid: ^4.4.0
  equatable: ^2.0.5
  
  # Animaciones
  flutter_animate: ^4.1.1+1
  
  # Gr치ficos
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  